### ISSUE TITLE
Cannot Use Your Library

### ISSUE THREAD

**Issue by vishal-chugh** [pavlospt/RoundedLetterView#6]
i cannot use this library 
same errors like above post are coming.

_My Dependency file:_
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.vishalchugh.krazysum"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:cardview-v7:23.3.0'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.github.pavlospt:roundedletterview:1.1'
}

```

**XML Code :** 
 ```
   <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:orientation="horizontal">

        <com.github.pavlospt.RoundedLetterView xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/rlv_name_view"
            android:layout_width="56dp"
            android:layout_height="56dp"
            app:backgroundColorValue="@color/green"
            app:titleColor="@android:color/white"
            app:titleSize="35dp"
            app:titleText="A" />

    </LinearLayout>
```

Error: 
C:\Users\Vishal Chugh\AndroidStudioProjects\myandroidprojects\KrazySum\app\src\main\res\layout\activity_play_field.xml
Error:(237) No resource identifier found for attribute 'backgroundColorValue' in package 'com.vishalchugh.krazysum'
Error:(237) No resource identifier found for attribute 'titleColor' in package 'com.vishalchugh.krazysum'
Error:(237) No resource identifier found for attribute 'titleSize' in package 'com.vishalchugh.krazysum'
Error:(237) No resource identifier found for attribute 'titleText' in package 'com.vishalchugh.krazysum'
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Android\sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

Please Help

**Comment by pavlospt** [comment]
Hello, thank you for your issue. I am aware of the problem, will try to resolve it asap.

**Comment by Shiza1aas** [comment]
I am using your library too, 

`   <com.github.pavlospt.roundedletterview.RoundedLetterView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/rlv_name_view"
        android:layout_width="56dp"
        android:layout_height="56dp"

        rlv_backgroundColor="#930e0e"
        rlv_titleColor="#fff"
        rlv_titleSize="35dp"
        rlv_titleText="A" />
`

But I am getting runtime error:

`
06-19 21:39:19.914 4823-4823/com.example.shahjahan.layouts E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.example.shahjahan.layouts, PID: 4823
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.shahjahan.layouts/com.example.shahjahan.layouts.MainActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class com.github.pavlospt.roundedletterview.RoundedLetterView
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:153)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:157)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class com.github.pavlospt.roundedletterview.RoundedLetterView
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                 at com.example.shahjahan.layouts.MainActivity.onCreate(MainActivity.java:17)
                                                                                 at android.app.Activity.performCreate(Activity.java:5312)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:153) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:157) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5637) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.pavlospt.roundedletterview.RoundedLetterView" on path: DexPathList[[zip file "/data/app/com.example.shahjahan.layouts-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.shahjahan.layouts-1, /vendor/lib, /system/lib]]
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:559)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                 at com.example.shahjahan.layouts.MainActivity.onCreate(MainActivity.java:17) 
                                                                                 at android.app.Activity.performCreate(Activity.java:5312) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:153) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:157) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5637) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) `

**Comment by pavlospt** [comment]
Version 1.2 is being uploaded as we speak. Resolves your issues :)
